# docker-compose.mysql_8_4_3.yml
# docker compose -f "docker-compose.mysql_8_4_3.yml" up -d --build
# Use root/root as user/password credentials
services:

  mysql_8_4_3:
    image: mysql:8.4.3
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartis_stat
    ports:
      - 3307:3306
    volumes:
      - ./mysql_8_4_3/data:/var/lib/mysql